### ISSUE TITLE
Problem with dynamic prop on `$subscribe`

### ISSUE THREAD

**Issue by thearabbit** [meteor-vue/vue-meteor-tracker#12]
Problem with dynamic prop on `$subscribe`
```js
data() {
            return {
                param: '',
                posts:[],
        },
        meteor: {
            $subscribe: {
                postsPub(){
                    return [this.param];
               }
            },
            posts(){
                return Posts.find().fetch();
            },
        },
methods:{
   handleParamChange(){
       // change param.......
   }
}
```
When I change `param` multi time, It get `Posts` in correct.

**Comment by Akryum** [comment]
I would advise you to filter the items in the `Posts.find()` part.

**Comment by thearabbit** [comment]
It means that `Posts.find({....selector.....})`!

**Comment by dolle39** [comment]
But is it possible to subscribe with a dynamic property? I have a lot of data and I need to filter some data to reduce subscription times.

**Comment by dolle39** [comment]
Okey, I found on the documentation how to use a dynamic property. But I only want to subscribe IF the dynamic property is not null. So for example: 

```
    meteor: {
      $subscribe: {
        'batch': function() {
         // HOW CAN I ENABLE SUBSCRIBE IF BATCHID IS NOT NULL?
          return [this.batchId]
        },
      },
```

Is that possible?

**Comment by bitk0der** [comment]
You should catch the null param on server side and if param null - don't publish, else - publish.
