### ISSUE TITLE
subsReady hook?

### ISSUE THREAD

**Issue by christophmayrhofer** [meteor-vue/vue-meteor-tracker#15]
I need to execute code when the subscription is ready. Is there some onSubscriptionReady hook that I can use? I know that there is  a $subReady reactive variable that I can use in the template, but I need it with a callback.

**Comment by Akryum** [comment]
You should be able to watch it. Maybe I'll add a way to put a hook.

**Comment by NathanielDavid** [comment]
How would you watch this.$subReady ?

**Comment by nilsi** [comment]
I could get it to work either, I had to do this very ugly workaround:

```
    meteor: {
        $subscribe: {
            'expertUsers': []
        },
        expertUsers() {
            return Meteor.users.find({}, {limit:4});
        }
    },
    watch: {
        'expertUsers': () => {
            //Getting Meteor context here.
            let subs = this.Meteor.default_connection._subscriptions;
            let subReady = Object.keys(subs).filter(key => (subs[key].name == "expertUsers") && subs[key].ready == true).length > 0;

            if (subReady) {
                console.log("ready");
            }
        }
    },
    data() {
        return {
            expertUsers: [],
            ....
       }
    }
```

**Comment by NathanielDavid** [comment]
Thank you, @nilsi.

**Comment by nilsi** [comment]
Oh interesting. If I do:

    watch: {
        'expertUsers': function () {
            console.log(this.$subReady.expertUsers);
        }
    }

Then I can simply check this.$subReady instead of checking manually in meteors subscriptions. 

If I use `: () => {` for the watch Im getting `window` and if I do `: function () {` Im getting Vue Component as my context (`this`).

**Comment by NathanielDavid** [comment]
Ah yes! This makes much more sense.

**Comment by Akryum** [comment]
As of `2.0.0-beta.1`, this should work as expected:

```js
  watch: {
    '$subReady.notes' (value) {
      console.log(value)
    },
  },
```
