### ISSUE TITLE
Check if all subscriptions are ready?

### ISSUE THREAD

**Issue by dolle39** [meteor-vue/vue-meteor-tracker#18]
I know you can check if a subscription is ready with the following:

`this.$subReady.thread`

But assume you have multiple subscriptions like below:

      $subscribe: {
        'subName1': [],
        'subName2: [],
        'subName3': [],
        'subName4': [],
        'subName5': [],
        'subName6': [],
        ....

I want to check if all subscrptions are ready, otherwise I want to show a Loading text.

Ofcourse I can check:

`let isReady = this.$subReady.subName1 && this.$subReady.subName2 && this.$subReady.subName3 ... && this.$subReady.subName6`

Is there perhaps a simpler way to check if all subscriptions are ready?

**Comment by Herteby** [comment]
I think this should work:
```
!_.contains(this.$subReady, false)
```
(replace "contains" with "includes" if you're using Lodash)

Add it to Vue for reuse:
```
Vue.prototype.$allReady = function(){
  return !_.contains(this.$subReady, false)
}
```

**Comment by dolle39** [comment]
Works lite a charm! Thanks!
