### ISSUE TITLE
Integration between Vue reactivity and Tracker reactivity

### ISSUE THREAD

**Issue by mitar** [meteor-vue/vue-meteor-tracker#3]
I am looking a bit how you are integrating Tracker with Vue and maybe I am misunderstanding something, it does not yet work as one would expect from perfect integration, because Vue reactivity is not really integrated with Tracker reactivity, no? So you cannot really use inside methods both Tracker reactive functions and access data and expect things to rerun, no?

Luckily, it seems that [Vue reactivity](https://vuejs.org/v2/guide/reactivity.html) has a similar model to Tracker reactivity. It also seems that Vue's state tracking is just a [mixin](https://github.com/vuejs/vue/blob/master/src/core/instance/state.js).

Here are some random ideas what we could do:
* for Meteor Vue components (or it could be an optional mixin), we could make it so that when Vue augments `data` with getters, we make them also Tracker getters (so when you set it, you invalidate both Vue and Tracker dependencies)
* we could monkey-patch Vue [Dep](https://github.com/vuejs/vue/blob/master/src/core/observer/dep.js#L12) to make it interact with [Tracker.Dependency](https://github.com/meteor/meteor/blob/devel/packages/tracker/tracker.js#L403), APIs are really similar
* but we probably do not care really that changes which happen inside Tracker dependencies are run on Tracker queue, we probably only want to provide the same API to reactive Meteor code so that it thinks it is running inside autorun, but it fact it is interacting with Vue Dep (and we leave to Vue to run it inside its own queue); this means that inside Vue, we could maybe misuse `Tracker.active` to set it to a fake computation which interacts with current Vue Dep
* for Minimongo integration, I wanted for a long time to make something there which would make it so that it is not needed to specify `fields` on the query to limit reactivity, but it would be limited automatically by the fact that you would use some values and not others, it seems that this could be very well integrated with Vue
* we should see how [Vue wraps mutation objects on arrays](https://vuejs.org/v2/guide/list.html#Mutation-Methods) and make it so that Minimongo changes trigger those mutations on Vue

What are your thoughts what is missing here for proper Meteor integration?

**Comment by Akryum** [comment]
Hey @mitar , a lot of useful thoughts on the integration. will definitively help with a potential vue-powered blaze! :+1: 

I initially decided to separate the Tracker and Vue reactive callbacks because I had very obscure issues by merging them into one callback (like other integrations does - and those I tried had similar issues). This caused unecessary/duplicate updates. I agree that we need to rethink the tracking integration and maybe completely replace Tracker internals with Vue Dep system.

**Comment by mitar** [comment]
So what I am currently thinking is that probably it would be better if we get Tracker and Minimongo to properly integrate with Vue, and then offer Blaze as a preprocessor (similar to how Jade is done for Vue). It would not be completely the same as Blaze 1.0, but it could have similar Handlebars syntax. Probably we would just name it Handlebars and not really Blaze. So Handlebars preprocessor for Vue.

**Comment by mitar** [comment]
BTW, do you know where is reactivity on accessing data in Vue registered? Looking at [this proxy](https://github.com/vuejs/vue/blob/master/src/core/instance/state.js#L231) I do not really get it.

**Comment by Akryum** [comment]
Vue setups special getters and setters that are wired to a Watcher instance that keep track of every other instances that use the getters, and the setters wake them up (plus Array methods like `push`). There is section about reactivity [in the guide](https://vuejs.org/v2/guide/reactivity.html).

**Comment by mitar** [comment]
Yes, I was more curious in the code, where this happens. Because I do not see that [this proxy](https://github.com/vuejs/vue/blob/master/src/core/instance/state.js#L231) is in any way special. [propse use defineReactive](https://github.com/vuejs/vue/blob/master/src/core/instance/state.js#L45), but not data.

**Comment by Akryum** [comment]
Because the data properties are stored inside a `$data` reactive object, that are then proxied to the component instance (see [here](https://github.com/vuejs/vue/blob/master/src/core/instance/state.js#L202)).

**Comment by mitar** [comment]
Hm, I think it is [this call](https://github.com/vuejs/vue/blob/master/src/core/instance/state.js#L92) which makes it proxied. OK.

**Comment by mitar** [comment]
Hm, I tried to [make a simple test](https://github.com/mitar/vue-test), to try to integrate Tracker properly, but I am getting the following error:

```
[Vue warn]: Failed to mount component: template or render function not defined. 
(found in root instance)
```

Probably some beginner issue. I am new to Vue. Any hint?

**Comment by mitar** [comment]
I made progress. I have full Tracker compatibility version implemented on top of Vue's observer:
* it needs for now a fork of Vue: https://github.com/vuejs/vue/pull/4652
* code: https://github.com/mitar/vue-test/blob/master/packages/tracker/tracker.js
* example app: https://github.com/mitar/vue-test

**Comment by mitar** [comment]
It would be great if Meteor supported [overriding packages](https://github.com/meteor/meteor/issues/5757). Because for now the only way to override the package is to put it inside `packages`. But this is not really a nice way to distribute this new implementation of Tracker.

**Comment by Akryum** [comment]
So far, you absolutely need those Vue changes?

**Comment by mitar** [comment]
Depending what the goal is. For 100% compatibility, probably yes. I definitely need access to Vue and Watcher symbols. Now, we could probably monkey patch more. The issue is the lack of support for after flush callbacks and the while loop around.

**Comment by Akryum** [comment]
Maybe `nextTick` could do?

**Comment by mitar** [comment]
Depending if we want 100% compatibility with Tracker and the same order of how dependencies are processed (especially outside rendering/Blaze/Vue dependencies).

One option I was considering initially was that we would have two queues, Tracker and Vue, and then just integrate Tracker's dependency with Vue dependency objects. The downside with this is that Vue would not invalidate Tracker's context then. So it would be only one directional. Now it works in both directions. You could have something like:

```javascript
count() {
  Tracker.autorun(() => {
    counter.set(this.buttonLabel);
  });
  return counter.get();
}
```

And it would work. (No reason why one would do something like this, just an example.) When `buttonLabel` would change, `autorun` would rerun. When outside `count` would get invalidated, internal `autorun` would stop. Exactly how one was used in Meteor/Blaze/Tracker.

I think this is really powerful.

**Comment by Akryum** [comment]
I was wondering, did you try running blaze with this?

**Comment by mitar** [comment]
Yes, of course. I run all Tinytests, the whole Meteor suite of tests, successfully (so Blaze tests included, and Blaze was used to render Tinytest UI).

**Comment by Herteby** [comment]
Why include Blaze though? Other than backwards compatibility with Meteor packages?

Wouldn't Vue + Tracker integration be enough?

**Comment by green-coder** [comment]
As far as I recall, the author of Vue proposed the solution of using a temporary fork until he accepts the PR in the long run.

**Comment by Akryum** [comment]
The big blocking issue right now is override meteor core packages.

Le mar. 27 juin 2017 16:50, Vincent Cantin <notifications@github.com> a
écrit :

**Comment by Herteby** [comment]
@Akryum What about just monkeypatching Tracker though?

**Comment by mitar** [comment]
Yes, we could just make it so that one hast to git submodule our tracker into `packages`. Probably this is the easiest way. And we can use a fork.

> Btw, why include Blaze? Other than backwards compatibility with Meteor packages?

There is no need to include Blaze. Where do you see it? [It is not here](https://github.com/mitar/vue-test/blob/master/.meteor/packages). (It is only one server side, I think, because Meter still adds it on the server side.)

**Comment by Herteby** [comment]
There is the possibility to [create tracks](https://docs.meteor.com/commandline.html#meteorpublishrelease) I guess. But I imagine that could be even more trouble than requiring people to manually clone tracker into packages/...

**Comment by mitar** [comment]
@Akryum: What is your take on how to integrate Minimongo the best? Now that we have proper Tracker support, it means that if you do `collection.find().fetch()` inside Vue computed function, it will rerun on every change, as expected. But what should we do if you return `collection.find()`? Should we do anything smart, or just call `fetch()` on it and freeze it? I see that you are doing in your approach something with freezing, why?

**Comment by mitar** [comment]
I have finished integrating Tracker with Vue. I think the result looks amazing. There are some internals we could continue improving, but I think that interface for developers works well.

To showcase it, I implemented [TodoMVC](https://github.com/meteor-vue/todomvc) in it. See [this file](https://github.com/meteor-vue/todomvc/blob/master/client/todos-display.vue) for an example of Vue component using familiar Meteor concepts, like reactivity, subscriptions and methods. (And also some custom packages, to show how they continue working as they worked in Blaze.)

Some [instructions how to use it can be found here](https://github.com/meteor-vue/guide). After more people tested it and more feedback, we can work on putting this into a package and more reusable form.

Comments and feedback welcome.

One potential step (which I am not planing to do personally, but would invite somebody to do) is to convert spacebars compiler to convert Blaze template syntax to Vue templates, in a similar way how [Vue allows to use Pug/Jade](https://vuejs.org/v2/guide/single-file-components.html).

**Comment by sethmurphy18** [comment]
So how close is this? Where are we at now? I am using this package, trying to recreate the classic [Meteor Todos](https://github.com/meteor/todos) app in Vue. I have the UI. My issue is with Tracker and Vue ironically enough. I can only subscribe to 1 subscription at a time. It's rather limiting.

**Comment by Herteby** [comment]
@sethmurphy18 What happens if you subscribe to more than one?

**Comment by sethmurphy18** [comment]
@Herteby The second subscription does nothing. It just returns undefined, and I know the data I am pulling is there. I can see it the Meteor shell. One sec, I am going to put what I have so far up so others can see what I am getting. I'm trying to stick as close to download and go as I can, so I am trying to avoid the fork, although I am not knocking the work @mitar has done.

**Comment by sethmurphy18** [comment]
Ok code is [here](https://github.com/eagerestwolf/todos-vue-meteor)

**Comment by Herteby** [comment]
@sethmurphy18 Hmm, I don't see any place where you subscribe to two things at once.
[This seems wrong though](https://github.com/eagerestwolf/todos-vue-meteor/blob/a0f7111f9f970c391295e03e24d6a854e6848efa/imports/ui/pages/ListPage.vue#L45). Vue doesn't have a "ready" hook. It has "mounted" and "created".

Personally I use [my own package](https://github.com/Herteby/grapher-vue) though.

**Comment by sethmurphy18** [comment]
Right, I was following the guide on here, thinking maybe if I split the 2 subs. I did revert it back to the standard though. That page is actually where I need to subscribe to 2 things. It's a hybrid subscription. I have been considering using vuex for the whole thing though.

**Comment by sethmurphy18** [comment]
Your package has me intrigued though...looking into it now. Reminds me a lot of `meteor-react-data`

**Comment by mitar** [comment]
This is done. I am using this in my new apps.
