### ISSUE TITLE
Meteor data not triggering `watch` and `computed` dependencies (v2.0.0-beta.3)

### ISSUE THREAD

**Issue by mizzao** [meteor-vue/vue-meteor-tracker#34]
After updating from v1.2.3, I am much happier about the cleaner code and reduction of redundant `data` keys. However, there are a couple of Vue modules that are no longer working as before and I tracked them down to having `watch` and `computed` values that depend on the keys that were previously listed in `data() { return { foo: ... } }` but are now generated by `meteor: { foo: ... }`.

All template code that depends on the `meteor` data keys still work fine.

Is this a bug or something I'm doing wrong? Happy to create a reproduction but wanted to quickly check if this was an actual issue first.

EDIT: just saw that the `computed` code was added in beta.3. Maybe it needs some tests :)

**Comment by mizzao** [comment]
@Akryum, is this an actual issue or did I do something wrong?

**Comment by richard-fairthorne** [comment]
Is this why I cannot see updates to reactive variables in the vue debugger under chrome?

**Comment by mitar** [comment]
(Just to shamelessly plug an alternative here, which is to use `Tracker` ported to Vue reactivity, as [described here](https://github.com/meteor-vue/guide).)

**Comment by mizzao** [comment]
@mitar I trust all your products, but does that package do everything that this one does, or something slightly different?

**Comment by mizzao** [comment]
> (Just to shamelessly plug an alternative here, which is to use `Tracker` ported to Vue reactivity, as [described here](https://github.com/meteor-vue/guide).)

**Comment by mitar** [comment]
It does it in a different way (requires Vue fork). To my understanding it provides the same features, but with different approach.
