### ISSUE TITLE
$subscribe is not reactive based on other data

### ISSUE THREAD

**Issue by vilipwong** [meteor-vue/vue-meteor-tracker#35]
Version: 2.0.0-beta.3
Vue version: 2.5.16,
OS: Ubuntu,
Browser: Chrome

Subscriptions inside $subscribe is not reactive ?

for example:

On page load, it takes a few seconds for subscribe data to get published and send to frontend. 

```
       $subscribe: {
            'food': function(){
                // drink data here is not reactive
                let drink = Drinks.findOne({user_id: Meteor.userId()});
                return [ {drink_id: drink._id} ];
            }
        },
        drink: function(){
           // drink data here is reactive
            let drink = Drinks.findOne({user_id: Meteor.userId()});
            return drink;
        }
```

Anyone facing this issue ? Or my way is wrong ? 

Please advise. Thanks !

**Comment by Akryum** [comment]
Try:

```js
let drink = this.drink || {};
```

**Comment by Akryum** [comment]
Yeah, forgot to change the documentation after [this breaking change](https://github.com/meteor-vue/vue-meteor-tracker/releases/tag/v2.0.0-beta.3).

**Comment by vilipwong** [comment]
I see. the params is reflecting correctly now after i wrap them in an array.

But $subscribe is still not reactive. I have tried with Meteor.userId also, it does not rerun when data changes.

I resolved to calling ``this.$subscribe`` in mounted hook :

```this.$subscribe('my-sub', () => [{drink_id: this.drinkId}, {sort: {updated_at: -1}, limit: 5}])```

**Comment by runarberg** [comment]
I am facing a similar issue:

```js
import CollectionA from '/imports/collections/a.js';
import CollectionB from '/imports/collections/b.js;

export default {
  params: {
    paramA: { type: String, default: '' },
  },

  meteor: {
    $subscribe: {
      'subscription-a''() {
        return [this.paramA];
      },
      'subscription-b'() {
        // This publication accepts an array of ids from CollectionA.
        // Here is the bug: We never react on changes in CollectionA.
        return [CollectionA.find().map(a => a.id)];
      },
    },

    a() {
      return CollectionA.find();
    },

    b() {
      return CollectionB.find();
    },
  },
};
```
I want `subscription-b` to resubscribe with an array of ids from `CollectionA` once 'subscription-a' is ready. However, `subscription-b` is not renewed when `CollectionA` changes, resulting in `subscription-b` never resubscribing with the new values from `CollectionA`.

In other words: `subscription-b` is not reactive based on `CollectionA` even though the subscription function for `subscription-b` depends on `CollectionA`

**Comment by Akryum** [comment]
I can't reproduce in the latest version.
