### ISSUE TITLE
Add official way to override subscribe function

### ISSUE THREAD

**Issue by nathantreid** [meteor-vue/vue-meteor-tracker#42]
Could you add an official way to override the `subscribe` function? I'm currently using v1.2.3, and I implement my own override like so:
``` js
Vue.config.meteor.subscribe = function (index, publication) {
  if (typeof publication === 'string') {
    return Meteor.subscribe(publication);
  }
  return publication.subscribe();
};
```

The reason for this is that I use my [`meteor-publication`](https://github.com/nathantreid/meteor-publication) package, which lets me avoid using magic strings for the publications (I use it in conjunction with TypeScript to enforce the parameter types passed to the publications):
``` ts
import slideThumbnailPublication from '../publications/slideThumbnail';
  //...
  meteor: {
    $subscribe: {
      subscribedThumbnail() {
        return [slideThumbnailPublication.withData(this.slide._id)];
      },
    },
  //...
```

If possible, I would like an official way to override the subscribe function so I don't have to worry about it not being possible at all in future versions.

**Comment by Akryum** [comment]
You can already override the subscribe function with `Vue.config.meteor.subscribe`. Maybe I misunderstood your question?

**Comment by nathantreid** [comment]
No, you didn't misunderstand - I somehow missed that this is already documented in the README as the way to override the subscribe function. My apologies!
