### ISSUE TITLE
this undefined in Reactive data

### ISSUE THREAD

**Issue by harry-73** [meteor-vue/vue-meteor-tracker#76]
I use vue3 and vue-meteor-tracker 3.0.0beta3.

When I try to use 'this' in Reactive data, i got undefined. It worked with vue2.6.14.

**Comment by Akryum** [comment]
Could you try again with 3.0.0-beta.4? :pray:

**Comment by harry-73** [comment]
I confirm. Now, it works. Thanks.

**Comment by harry-73** [comment]
In fact, it works when I use for example 'this.$store...' but not if I use 'this' with variables defined into 'data()' or 'computed()'. It is still undefined.

**Comment by harry-73** [comment]
@Akryum had you time to look at it?

Thanks
